tetragon:
  enabled: true
  enableProcessCred: true
  enableProcessNs: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

  export:
    mode: stdout
    filenames: [tetragon.log]

tetragonOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  prometheus:
    serviceMonitor:
      enabled: true
