apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy
  namespace: monitoring
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - alloy.home.lab
  rules:
    - backendRefs:
        - name: alloy
          port: 12345
