appName: external-secrets
namespace: external-secrets
project: platform
repoURL: oci://ghcr.io/external-secrets/charts/external-secrets
targetRevision: 2.5.0
chartPath: .
syncWave: "1"
serverSideApply: "true"
