installCRDs: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

certController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
