# ClusterSecretStore for Vault KV v2 secrets (static secrets)
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kv
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
---
# ClusterSecretStore for Vault dynamic secrets (database engine)
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-database
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "database"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
