# 1. "Viewer" ClusterRole for human users (Read-Only UI Access)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-viewer
rules:
  - apiGroups: ["*"]
    resources:
      [
        "notebooks",
        "pods",
        "services",
        "deployments",
        "jobs",
        "workflows",
        "experiments",
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kubeflow.org", "pipelines.kubeflow.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
# 2. Restrictive Profile Template
# Use this profile structure in your GitOps repo to enforce limits
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: limited-user-example
spec:
  owner:
    kind: User
    name: "nuno.o.fernandes@outlook.pt"
  resourceQuotaSpec:
    hard:
      requests.cpu: "2"
      requests.memory: "4Gi"
      services.loadbalancers: "0"
      requests.storage: "10Gi"
