apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: tailscale
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-kv
  namespace: tailscale
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: tailscale
          serviceAccountRef:
            name: vault-auth
