# GitHub OAuth / App credentials (static, KV v2)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-github
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: backstage-github
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: backstage/github
        property: client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: backstage/github
        property: client_secret
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: backstage/github
        property: app_id
    - secretKey: GITHUB_PRIVATE_KEY
      remoteRef:
        key: backstage/github
        property: private_key
---
# Dynamic PostgreSQL credentials (Vault database secrets engine)
# Refreshed at 30m — well within the 1h TTL configured on the Vault role.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-database
  namespace: backstage
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-database
    kind: ClusterSecretStore
  target:
    name: backstage-database
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: creds/backstage-role
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: creds/backstage-role
        property: password
