apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backstage
  namespace: backstage
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - backstage.home.lab
  rules:
    - backendRefs:
        - name: backstage
          port: 7007
