apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubeflow-dashboard
  namespace: kubeflow
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - kubeflow.home.lab
  rules:
    backendRefs:
      - name: istio-ingressgateway
        namespace: istio-system
        port: 80
