apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-credentials
  namespace: pihole
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: pihole-web-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pihole/credentials
        property: password
