apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  # These values are never used, but the Secret must exist
  # for the Helm chart to start the Pod.
  client_id: "placeholder"
  client_secret: "placeholder"
