apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: Tempo
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
        access: proxy
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: Loki
            tags:
              - key: service.name
                value: service
              - key: k8s.namespace.name
                value: namespace
          tracesToMetrics:
            datasourceUid: Prometheus
