apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
  namespace: vault
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - vault.apps.internal
  rules:
    - backendRefs:
        - name: vault-ui
          port: 8200
