apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: backstage
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-kv
  namespace: backstage
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: backstage
          serviceAccountRef:
            name: vault-auth
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-database
  namespace: backstage
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: database
      version: v1
      auth:
        kubernetes:
          mountPath: kubernetes
          role: backstage
          serviceAccountRef:
            name: vault-auth
